### ISSUE TITLE
ESV API fails to find "Ester"

### ISSUE THREAD

**Issue by emathia** [khornberg/readingplans#2]
Thank you for making this json list of bible reading available.  It makes it possible for me to look up the daily Bible reading without having to download a special app or navigate many clicks.  I use the esveverydayintheword.json plan.

I noticed today (2020-08-18) that the ESV API returns nothing because it cannot parse "Ester".  It returns correctly using the canonical spelling "Esther".  It is not a big deal because it is a short book and only happens 2-3 days.  I just thought you might like to know.

**Comment by khornberg** [comment]
Thanks for the report
I've fix it in the latest version

**Comment by khornberg** [comment]
This is fixed
